server:
  contextPath: /homeWorkPart2
spring:
  datasource:
    driverClassName: org.postgresql.Driver
    jdbcUrl: jdbc:postgresql://localhost:5432/contact
    username: homeWorkPart2
    password: root
  jpa:
   # hibernate.ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        cache:
          use_second_level_cache: false
          use_structured_entities: true
        generate_statistics: false
pageSize: 100
